### ISSUE TITLE
How to Change the Font

### ISSUE THREAD

**Issue by thatgrrl** [kayleconut/listfauxgraphy#1]
I have listfauxgraphy set up, even managed to change colours. 

I'm not sure what code exactly I need to change the font. I tried just adding code but nothing changed. I'd like to change it to a monospaced font like Inconsolas, one of the fonts I like using for making ASCII art. 

Thank you for making it public. I wanted to make something a bit like a web directory or a page to list resources, etc. I think this will work well for me, on my skill level of simple. :)

**Comment by kayleconut** [comment]
The font is stored in a variable called "--bodyfont" under the root selector (line 10 in style.css). It's going to be wonky if you try to add code somewhere else since you're trying to define a font twice!
